### ISSUE TITLE
update import RAD51C

### ISSUE THREAD

**Issue by elenikiachaki** [ELELAB/mavisp_data_collection#226]
Addition of local_interactions with RAD51B:
- MUTATEX:
`/data/raw_data/computational_data/mutatex_data/vus/rad51c/complexes/rad51b/AF3_BCDX2/mavisp_poslist/`

- ROSETTA:
`/data/raw_data/computational_data/rosetta_data/vus/rad51c/complexes/rad51b/AF3_BCDX2/talaris2014_flexddg_large/`

**Comment by elenapapaleo** [comment]
imported in mavisp_data_saturation, csv will be updated 13/12/2024
