### ISSUE TITLE
import FAS, XPC, CDH10 and CDH11

### ISSUE THREAD

**Issue by pablosanchezizquierdo** [ELELAB/mavisp_data_collection#227]
FAS:
cancermuts:
/data/raw_data/computational_data/cancermuts_data/cosmic_tsg/FAS/pancancer_clinvar_saturation/17102024

mutatex:
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/fas/free/stability/mutatex_runs/AF_54-335/model_v4/saturation/P25445_table/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_tsg/fas/free/AF_54-335/model_v4/

XPC:
cancermuts:
/data/raw_data/computational_data/cancermuts_data/cosmic_tsg/XPC/pancancer_clinvar_saturation/17102024

mutatex:
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/xpc/free/stability/mutatex_runs/AF_159-326/model_v4/saturation/Q01831_table/
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/xpc/free/stability/mutatex_runs/AF_525-868/model_v4/saturation/Q01831_table/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_tsg/xpc/free/AF_159-326/model_v4/
/data/raw_data/computational_data/rasp_data/cosmic_tsg/xpc/free/AF_525-868/model_v4/

CDH10:
cancermuts:
/data/raw_data/computational_data/cancermuts_data/cosmic_tsg/CDH10/pancancer_clinvar_saturation/17102024

mutatex:
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/cdh10/free/stability/mutatex_runs/AF_52-638/model_v4/saturation/Q9Y6N8_table/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_tsg/cdh10/free/AF_52-638/model_v4/

CDH11:
cancermuts:
/data/raw_data/computational_data/cancermuts_data/cosmic_tsg/CDH10/pancancer_clinvar_saturation/17102024

mutatex:
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/cdh11/free/stability/mutatex_runs/AF_57-643/model_v4/saturation/P55287_table/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_tsg/cdh11/free/AF_57-643/model_v4/

**Comment by kar0liina** [comment]
Imported XPC, CDH10, CDH11. 
FAS to be rerun/changed before next import.

**Comment by kar0liina** [comment]
Imported XPC, CDH10, CDH11.
FAS to be rerun/changed before next import.

**Comment by pablosanchezizquierdo** [comment]
FAS issue is fixed now

**Comment by kar0liina** [comment]
Imported FAS
