### ISSUE TITLE
import SLC34A2, TRI33, TNFRSF14

### ISSUE THREAD

**Issue by DegnKristine** [ELELAB/mavisp_data_collection#233]
SLC34A2 
DIR: `/data/user/shared_projects/mavisp/SLC34A2`

cancermuts:
`/data/raw_data/computational_data/cancermuts_data/cosmic_tsg/SLC34A2/pancancer_clinvar_saturation/21102024/`

mutatex:
`/data/raw_data/computational_data/mutatex_data/cosmic_tsg/slc34a2/free/stability/mutatex_runs/AF_86-610/model_v3/saturation/O95436_table/`

rasp:
`/data/raw_data/computational_data/rasp_data/cosmic_tsg/slc34a2/free/AF_86-610/model_v2`

TNFRSF14
DIR: `/data/user/shared_projects/mavisp/TNFRSF14`

cancermuts:
`/data/raw_data/computational_data/cancermuts_data/cosmic_tsg/TNFRSF14/pancancer/21102024/`

mutatex: 
`/data/raw_data/computational_data/mutatex_data/cosmic_tsg/tnfrsf14/free/stability/mutatex_runs/AF_39-185/model_v3/saturation/Q92956_table/`

rasp: 
`/data/raw_data/computational_data/rasp_data/cosmic_tsg/tnfrsf14/free/AF_39-185/model_v2/`

TRIM33
DIR: `/data/user/shared_projects/mavisp/TRI33M`

cancermuts:
`/data/raw_data/computational_data/cancermuts_data/cosmic_tsg/TRIM33/pancancer_clinvar_saturation/21102024/`

mutatex:
* `/data/raw_data/computational_data/mutatex_data/cosmic_tsg/trim33/free/stability/mutatex_runs/AF_272-478/model_v3/saturation/Q9UPN9_table/`
* `/data/raw_data/computational_data/mutatex_data/cosmic_tsg/trim33/free/stability/mutatex_runs/AF_957-1090/model_v3/saturation/Q9UPN9_table/`

rasp:
* `/data/raw_data/computational_data/rasp_data/cosmic_tsg/trim33/free/AF_272-478/model_v2/output/predictions/`
* `/data/raw_data/computational_data/rasp_data/cosmic_tsg/trim33/free/AF_957-1090/model_v2/output/predictions/`

**Comment by kar0liina** [comment]
Entries Imported.
