### ISSUE TITLE
Update ARID1A ensemble 

### ISSUE THREAD

**Issue by kar0liina** [ELELAB/mavisp_data_collection#234]
ptm.md:
/data/user/shared_projects/mavisp/ARID1A/ptm.md/mutatex/

/data/user/shared_projects/mavisp/ARID1A/ptm.md/nacess/

mutatex 25 frames: 
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/arid1a/free/AF_1005-1110/saturation_ensemble/

psn-paths: 
/data/user/shared_projects/mavisp/ARID1A/simulations_analysis/free/AF_1005-1110/replicate1/CHARMM36/md/8.psn/pyinteraph2/acPSN/full_traj/path_analysis

rasp: 
/data/raw_data/computational_data/rasp_data/cosmic_tsg/arid1a/free/AF_1005-1110/model_v4/saturation_ensemble

**Comment by elenapapaleo** [comment]
all imported in mavisp_data_saturation and will be included in the mavisp.py run on the 2nd of November
