### ISSUE TITLE
Import VHL ensemble mode 

### ISSUE THREAD

**Issue by pablosanchezizquierdo** [ELELAB/mavisp_data_collection#235]
VHL:
ptm.md:
/data/user/shared_projects/mavisp/VHL/ptm.md/mutatex/
/data/user/shared_projects/mavisp/VHL/ptm.md/nacess/

mutatex:
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/vhl/free/AF_58-213/saturation_ensemble/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_tsg/vhl/free/AF2_58_213/saturation_ensemble/model_v4/

psn-paths:
/data/user/shared_projects/mavisp/VHL/simulations_analysis/free/AF_58-213/replicate1/CHARMM22star/md/8.psn/pyinteraph2/acPSN/full_traj/path_analysis/

**Comment by elenapapaleo** [comment]
done and will be included in the mavisp.py update on 01/11/2024
