### ISSUE TITLE
Updated BCL10 ensemble

### ISSUE THREAD

**Issue by kar0liina** [ELELAB/mavisp_data_collection#242]
ptm.md:
/data/user/shared_projects/mavisp/BCL10/ptm.md/mutatex/

/data/user/shared_projects/mavisp/BCL10/ptm.md/nacess/

mutatex 25 frames:
/data/raw_data/computational_data/mutatex_data/cosmic_tsg/bcl10/free/AF_10-117/saturation_ensemble/

psn-paths:
/data/user/shared_projects/mavisp/BCL10/simulations_analysis/free/AF_10-117/replicate1/CHARMM36/md/8.psn/pyinteraph2/acPSN/full_traj/path_analysis/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_tsg/bcl10/free/saturation_ensemble/AF_10-117/model_v2/

**Comment by elenapapaleo** [comment]
imported and included in the current run with mavisp.py
