### ISSUE TITLE
import KDR and KIT

### ISSUE THREAD

**Issue by lorenzo-22** [ELELAB/mavisp_data_collection#256]
KDR:
cancermuts:
/data/raw_data/computational_data/cancermuts_data/cosmic_ocg/kdr/pancancer_clinvar_saturation/26112024/

mutatex:
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kdr/free/stability/mutatex_runs/AF_30-467/model_v3/saturation/P35968_table/
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kdr/free/stability/mutatex_runs/AF_484-755/model_v3/saturation/P35968_table/
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kdr/free/stability/mutatex_runs/AF_768-789/model_v3/saturation/P35968_table/
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kdr/free/stability/mutatex_runs/AF_822-937/model_v3/saturation/P35968_table/
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kdr/free/stability/mutatex_runs/AF_1000-1166/model_v3/saturation/P35968_table/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_ocg/free/AF_30-467/v3_model
/data/raw_data/computational_data/rasp_data/cosmic_ocg/free/AF_484-755/v3_model
/data/raw_data/computational_data/rasp_data/cosmic_ocg/free/AF_768-789/v3_model
/data/raw_data/computational_data/rasp_data/cosmic_ocg/free/AF_822-937/v3_model
/data/raw_data/computational_data/rasp_data/cosmic_ocg/free/AF_1000-1166/v3_model

KIT:
cancermuts:
/data/raw_data/computational_data/cancermuts_data/cosmic_ocg/kit/pancancer_clinvar_saturation/23112024/

mutatex:
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kit/free/stability/mutatex_runs/AF_34-507/model_v3/saturation/P10721_table/
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kit/free/stability/mutatex_runs/AF_520-549/model_v3/saturation/P10721_table/
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kit/free/stability/mutatex_runs/AF_575-690/model_v3/saturation/P10721_table/
/data/raw_data/computational_data/mutatex_data/cosmic_ocg/kit/free/stability/mutatex_runs/AF_762-940/model_v3/saturation/P10721_table/

rasp:
/data/raw_data/computational_data/rasp_data/cosmic_ocg/kit/free/AF_34-507/v3_model
/data/raw_data/computational_data/rasp_data/cosmic_ocg/kit/free/AF_520-549/v3_model
/data/raw_data/computational_data/rasp_data/cosmic_ocg/kit/free/AF_575-690/v3_model
/data/raw_data/computational_data/rasp_data/cosmic_ocg/kit/free/AF_762-940/v3_model

**Comment by kar0liina** [comment]
Proteins Imported
