### ISSUE TITLE
Import RAD51D and XRCC2

### ISSUE THREAD

**Issue by elenikiachaki** [ELELAB/mavisp_data_collection#257]
**RAD51D:**
- Cancermuts: 
`/data/raw_data/computational_data/cancermuts_data/mavisp_others/rad51d/pancancer_clinvar_saturation/11112024
`
- Mutatex: 
`/data/raw_data/computational_data/mutatex_data/mavisp_others/rad51d/free/stability/mutatex_runs/AF_1-315/model_v3/saturation/O75771_table`

- RasP:
`/data/raw_data/computational_data/rasp_data/mavisp_others/rad51d/free/AF_1-315/model_v2
`

**XRCC2:**
- Cancermuts:
`/data/raw_data/computational_data/cancermuts_data/mavisp_others/xrcc2/pancancer_clinvar_saturation/11112024
`
- Mutatex:
`/data/raw_data/computational_data/mutatex_data/mavisp_others/xrcc2/free/stability/mutatex_runs/AF_7-280/model_v3/saturation/O43543_table`

- RasP:
`/data/raw_data/computational_data/rasp_data/mavisp_others/xrcc2/free/AF_7-280/model_v2`

**Comment by kar0liina** [comment]
Proteins Imported
